seed: 42
output_dir: ./outputs/
exp_name: pretrain
resume: null # provide a checkpoint path
device: cuda

model:
  seq_len: 2250
  patch_size: 75
  num_leads: 12
  # mask_ratio: 0.75
  norm_pix_loss: true

dataset:
  train_csv: ./data/index.csv
  
  # cols
  path_col: path
  fs_col: fs

  leads: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
  fs: 250
  len: 2500
  len_sec: 10

  train_transforms:
  - random_crop:
      crop_length: 2250
  - highpass_filter:
      fs: 250
      cutoff: 0.67
  - lowpass_filter:
      fs: 250
      cutoff: 40
  - standardize:
      axis: [-1, -2]

dataloader:
  batch_size: 16
  num_workers: 8
  pin_memory: True

train:
  total_epochs: 20
  accum_iter: 1
  warmup_epochs: 3
  min_lr: 0
  blr: 1.5e-4
  lr: 1.5e-4
  weight_decay: 0.01
  optimizer: adamw
  optimizer_kwargs:
    betas: [0.9, 0.95]
